### ISSUE TITLE
pia-port-forward typo?

### ISSUE THREAD

**Issue by glorious1** [dak180/TrueNAS-Scripts#1]
pia-port-forward looks interesting.  It looks like you have 2 spellings: adapterName and adaptorName.  Is that intentional?  I guess if they are defined locally in each function, it can still work, but maybe confusing.

**Comment by dak180** [comment]
@glorious1 a search of the file for `adapterName` yields no matches.

**Comment by glorious1** [comment]
That's right.  Guess I was confused between adaptorName and tunnelAdapter.  Are they meant to be the same thing?  I don't find where adaptorName is set.

**Comment by dak180** [comment]
@glorious1 `adaptorName` is meant to only be used in local scopes within functions and gets set in each function that needs it. `tunnelAdapter` is set on the script level; the difference in names is so they do not step on each other.
