### ISSUE TITLE
Linux bash (may not be at all relevant)

### ISSUE THREAD

**Issue by mbuette** [dak180/TrueNAS-Scripts#2]
I'm not sure if this is at all relevant to you, given your "...specifically in FreeBSD" comment. But I ported `pia-port-forward.sh` to Debian GNU/Linux and ran into problems with line 163: the `| jq -Mre` produces a multi-line output and this breaks the assignment to the variable. Removing it produces a single line which can be assigned to $json. I got so frustrated, I even asked on StackExchange and somebody there told me "bash is bash" and I should tell you.

Otherwise: Thanks a lot for your work! I really dreaded modifying 912 lines of PIA scripts for my purpose (just simple PF), you made my live much easier!

**Comment by dak180** [comment]
@mbuette What version of bash are you running and exactly what error are you getting?  I have many times deliberately set a multi-line variable and have not had an issue; are you sure that you are not actually using ```dash``` masquerading as ```sh``` or ```bash```?

**Comment by mbuette** [comment]
I'm running Debian GNU/Linux 10.6 with bash `GNU bash, version 5.0.3(1)-release (x86_64-pc-linux-gnu)`. See StackExchange [here](https://unix.stackexchange.com/questions/622955/bash-noob-whats-wrong-with-this-line?noredirect=1#comment1165340_622955). But as I said, if it works on FreeBSD it's fine. Just wanted to let you know. You can close this Issue if everything is OK on the BSD-side of things :)

**Comment by dak180** [comment]
I use this every day and as far as I can tell it works perfectly here.
