### ISSUE TITLE
Fan Control Script How To

### ISSUE THREAD

**Issue by seniorm0ment** [dak180/TrueNAS-Scripts#5]
I downloaded the script and placed it in a folder in home dir.
Changed the defaultFile from 1 to 0 and saved.
Renamed from .tool to .sh
chmod +x on the file.

Then tried running via ./fancontrol.sh
And it says Please configure a config file location

How/where am I supposed to do this?

**Comment by dak180** [comment]
https://github.com/dak180/TrueNAS-Scripts/blob/master/FanControl.tool#L641 or `./fancontrol.tool -?`

**Comment by TushKutush** [comment]
Hello. Is it possible to use your script in OMV6, on m/p ASRook E3C226D2I?

**Comment by dak180** [comment]
@TushKutush The commands for the motherboard may be the same as the default, you would have to check with ASRook to know for sure; as for OMV6 no idea, I do not use it or test it so you will have to try.
